FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y scons python-pip python-dev build-essential

#RUN pip install scons
RUN pip install robotframework

COPY compile.sh .

CMD sh /compile.sh
